CREATE TABLE patients (
    patient_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR2(100) NOT NULL,
    age           NUMBER(3) CHECK (age >= 0),
    sex           VARCHAR2(10) CHECK (sex IN ('Male', 'Female', 'Other')),
    contact_info  VARCHAR2(255)
);

CREATE TABLE doctors (
    doctor_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR2(100) NOT NULL,
    specialization    VARCHAR2(100),
    contact_info      VARCHAR2(255),
    availability_status VARCHAR2(50) CHECK (availability_status IN ('Available', 'Unavailable'))
);
CREATE TABLE appointments (
    appointment_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id      NUMBER NOT NULL,
    doctor_id       NUMBER NOT NULL,
    appointment_date DATE NOT NULL,

    CONSTRAINT fk_appointment_patient FOREIGN KEY (patient_id) REFERENCES patients(patient_id) ON DELETE CASCADE,
    CONSTRAINT fk_appointment_doctor FOREIGN KEY (doctor_id) REFERENCES doctors(doctor_id) ON DELETE SET NULL
);
CREATE INDEX idx_appointment_patient ON appointments(patient_id);
CREATE INDEX idx_appointment_doctor ON appointments(doctor_id);


CREATE TABLE payments (
    payment_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id    NUMBER NOT NULL,
    appointment_id NUMBER NOT NULL,
    payment_status VARCHAR2(20) CHECK (payment_status IN ('Pending', 'Completed', 'Refunded')),
    amount        NUMBER(10,2) CHECK (amount >= 0),
    payment_date  DATE DEFAULT SYSDATE,
    payment_method VARCHAR2(20) CHECK (payment_method IN ('Cash', 'Card', 'Insurance')),

    CONSTRAINT fk_payment_patient FOREIGN KEY (patient_id) REFERENCES patients(patient_id) ON DELETE CASCADE,
    CONSTRAINT fk_payment_appointment FOREIGN KEY (appointment_id) REFERENCES appointments(appointment_id) ON DELETE CASCADE
);

CREATE INDEX idx_payment_patient ON payments(patient_id);
CREATE INDEX idx_payment_appointment ON payments(appointment_id);




CREATE TABLE prescriptions (
    prescription_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id         NUMBER NOT NULL,
    doctor_id          NUMBER NOT NULL,
    diagnosis         VARCHAR2(255),
    medication_details VARCHAR2(255),
    dosage            VARCHAR2(100),
    instructions      VARCHAR2(255),

    CONSTRAINT fk_prescription_patient FOREIGN KEY (patient_id) REFERENCES patients(patient_id) ON DELETE CASCADE,
    CONSTRAINT fk_prescription_doctor FOREIGN KEY (doctor_id) REFERENCES doctors(doctor_id) ON DELETE SET NULL
);

CREATE INDEX idx_prescription_patient ON prescriptions(patient_id);
CREATE INDEX idx_prescription_doctor ON prescriptions(doctor_id);






CREATE UNIQUE INDEX idx_username ON login(username);

CREATE TABLE checkup_details (
    checkup_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    patient_id NUMBER,
    appointment_id NUMBER,
    blood_pressure VARCHAR2(10),  -- e.g., '120/80'
    sugar_level VARCHAR2(10),     -- e.g., '110 mg/dL'
    temperature VARCHAR2(10),     -- e.g., '98.6°F'
    heart_rate NUMBER,            -- e.g., 72
    CONSTRAINT fk_checkup_patient FOREIGN KEY (patient_id) REFERENCES patients(patient_id) ON DELETE CASCADE,
    CONSTRAINT fk_checkup_appointment FOREIGN KEY (appointment_id) REFERENCES appointments(appointment_id) ON DELETE CASCADE
);


DOCTOR LOGIN:
-- Add all doctors who are not yet in doctor_login
INSERT INTO doctor_login (doctor_id, username, password)
SELECT d.doctor_id,
       'doctor_' || d.doctor_id,
       'defaultpass'
FROM doctors d
WHERE d.doctor_id NOT IN (SELECT doctor_id FROM doctor_login);

CREATE OR REPLACE TRIGGER trg_auto_doctor_login
AFTER INSERT ON doctors
FOR EACH ROW
BEGIN
    INSERT INTO doctor_login (doctor_id, username, password)
    VALUES (:NEW.doctor_id, 'doctor_' || :NEW.doctor_id, 'defaultpass');
END;
/


CREATE TABLE doctor_login (
    login_id     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    doctor_id    NUMBER UNIQUE NOT NULL,
    username     VARCHAR2(100) UNIQUE,
    password     VARCHAR2(100) NOT NULL,

    CONSTRAINT fk_doctor_login FOREIGN KEY (doctor_id)
        REFERENCES doctors(doctor_id)
        ON DELETE CASCADE
);



Receptionist Login:
CREATE TABLE receptionists (
    receptionist_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    contact_info VARCHAR2(255)
);


CREATE TABLE receptionist_login (
    login_id        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    receptionist_id NUMBER UNIQUE NOT NULL,
    username        VARCHAR2(100) UNIQUE,
    password        VARCHAR2(100) NOT NULL,

    CONSTRAINT fk_receptionist_login FOREIGN KEY (receptionist_id)
        REFERENCES receptionists(receptionist_id)
        ON DELETE CASCADE
);

CREATE OR REPLACE TRIGGER trg_auto_receptionist_login
AFTER INSERT ON receptionists
FOR EACH ROW
BEGIN
    INSERT INTO receptionist_login (receptionist_id, username, password)
    VALUES (:NEW.receptionist_id, 'receptionist_' || :NEW.receptionist_id, 'defaultpass');
END;
/







CREATE TABLE queue (
    queue_id SERIAL PRIMARY KEY,
    appointment_id INT NOT NULL,
    patient_id INT NOT NULL,
    enqueue_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) NOT NULL DEFAULT 'waiting',

    CONSTRAINT fk_appointment FOREIGN KEY (appointment_id)
        REFERENCES appointments(appointment_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_patient FOREIGN KEY (patient_id)
        REFERENCES patients(patient_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);	





CREATE OR REPLACE TRIGGER trg_after_payment_completed
AFTER INSERT OR UPDATE OF payment_status ON payments
FOR EACH ROW
DECLARE
    v_exists NUMBER;
BEGIN
    IF :NEW.payment_status = 'Completed' THEN
        SELECT COUNT(*) INTO v_exists
        FROM queue
        WHERE appointment_id = :NEW.appointment_id;

        IF v_exists = 0 THEN
            INSERT INTO queue (appointment_id, patient_id, status)
            VALUES (:NEW.appointment_id, :NEW.patient_id, 'waiting');
        END IF;
    END IF;
END;
/


ALTER TABLE queue ADD CONSTRAINT uq_queue_appointment UNIQUE (appointment_id);
INSERT INTO patients (name, age, sex, contact_info) VALUES
('Shehla Khan', 35, 'Female', 'shehla.khan@email.com, +92-300-1234567');
('Ahsan Raza', 28, 'Male', 'ahsan.raza@email.com, +92-321-7654321');
('Nida Hassan', 42, 'Female', 'nida.hassan@email.com, +92-333-9876543');

-- Insert dummy doctors
INSERT INTO doctors (name, specialization, contact_info, availability_status) VALUES
('Dr. Farhan Ahmed', 'Cardiology', 'farhan.ahmed@hospital.com, +92-345-1122334', 'Available'),
('Dr. Samina Iqbal', 'Dermatology', 'samina.iqbal@hospital.com, +92-356-2233445', 'Unavailable'),
('Dr. Hira Andleeb', 'Pediatrics', 'hira.andleeb@hospital.com, +92-377-9988776', 'Available');

-- Insert dummy appointments
INSERT INTO appointments (patient_id, doctor_id, appointment_date) VALUES
(1, 1, TO_DATE('2025-03-15', 'YYYY-MM-DD')),
(2, 2, TO_DATE('2025-03-18', 'YYYY-MM-DD')),
(3, 1, TO_DATE('2025-03-20', 'YYYY-MM-DD'));

-- Insert dummy payments
INSERT INTO payments (patient_id, appointment_id, payment_status, amount, payment_method) VALUES
(1, 1, 'Completed', 2500.00, 'Card'),
(2, 2, 'Pending', 1800.00, 'Cash'),
(3, 3, 'Completed', 3000.00, 'Insurance');

-- Insert dummy prescriptions
INSERT INTO prescriptions (patient_id, doctor_id, diagnosis, medication_details, dosage, instructions) VALUES
(1, 1, 'Hypertension', 'Amlodipine, Losartan', '5mg daily, 50mg daily', 'Take in the morning with water'),
(2, 2, 'Acne', 'Isotretinoin, Clindamycin', '20mg daily, Apply twice daily', 'Take after dinner with a full glass of water, Apply on affected areas'),
(3, 1, 'Diabetes', 'Metformin, Insulin', '500mg twice daily, 10 units before meals', 'Take with meals, Inject subcutaneously before meals');

-- Insert dummy login data
INSERT INTO login (username, password_hash, role) VALUES
('doctor_farhan', 'hashedpassword1', 'doctor'),
('doctor_samina', 'hashedpassword2', 'doctor'),
('doctor_hira', 'hashedpassword3', 'doctor'),
('reception_shehla', 'hashedpassword4', 'receptionist');


-- Insert dummy checkup details
-- Insert checkup details for Shehla Khan (Patient 1, Appointment 1)
INSERT INTO checkup_details (patient_id, appointment_id, blood_pressure, sugar_level, temperature, heart_rate) 
VALUES (1, 1, '130/85', '140 mg/dL', '99.1°F', 78);

-- Insert checkup details for Ahsan Raza (Patient 2, Appointment 2)
INSERT INTO checkup_details (patient_id, appointment_id, blood_pressure, sugar_level, temperature, heart_rate) 
VALUES (2, 2, '110/70', '90 mg/dL', '98.4°F', 72);

-- Insert checkup details for Nida Hassan (Patient 3, Appointment 3)
INSERT INTO checkup_details (patient_id, appointment_id, blood_pressure, sugar_level, temperature, heart_rate) 
VALUES (3, 3, '125/80', '160 mg/dL', '98.9°F', 85);
